# Generated by Django 5.0.3 on 2024-03-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='produce',
            new_name='product',
        ),
    ]
